version: "3"
services: 
  redis:
    image: redis
    networks:
      - webnet
    volumes:
      - redis-data:/var/lib/redis/data
    command: "redis-server"
  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    env_file:
      - ./.env
    restart: always
    networks:
      - webnet
    depends_on:
      - redis
      - db
    ports:
      - "5000:5000"
networks:
  webnet:
volumes:
  postgres-data:
  redis-data: